import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const require=createRequire(import.meta.url);const ts=require('typescript');
function load(name){const source=fs.readFileSync(new URL(`../src/components/admin/${name}`,import.meta.url),'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;const exports={};vm.runInNewContext(output,{exports,require,URLSearchParams});return exports;}
test('period survives URL reload and preserves unrelated filters',()=>{const {readPeriod,periodQuery}=load('navigation.ts');const query=periodQuery('q=salud',{days:'custom',start:'2026-10-01',end:'2026-10-05'});assert.equal(new URLSearchParams(query).get('q'),'salud');const result=readPeriod(new URLSearchParams(query));assert.equal(result.days,'custom');assert.equal(result.start,'2026-10-01');assert.equal(result.end,'2026-10-05');});
test('related news links accept missing public URL and reject absent IDs',()=>{const {relatedNewsHref}=load('navigation.ts');assert.equal(relatedNewsHref({noticia_id:42}),'/admin/news?detail=42');assert.equal(relatedNewsHref({noticia_id:null}),null);});
test('topic selection remains selected while its options are loading',()=>{const {renderToStaticMarkup}=require('react-dom/server');const React=require('react');const {TopicFilter}=load('TopicFilter.tsx');for(const topics of [[],[{id:7,nombre:'Salud'}]]){const html=renderToStaticMarkup(React.createElement(TopicFilter,{selected:'7',topics,onChange:()=>{}}));assert.match(html,/<option value="7" selected="">/);}});
test('drawer focus loops, Escape closes, and cleanup restores trigger',()=>{const {manageDrawerFocus}=load('navigation.ts');let focused='trigger';let key;let closed=false;const doc={get activeElement(){return focused;},addEventListener:(_type,fn)=>key=fn,removeEventListener:()=>{key=null;}};const first={getClientRects:()=>[{}],focus(){focused=first;}},last={getClientRects:()=>[{}],focus(){focused=last;}};const trigger={focus(){focused='trigger';}};const panel={querySelectorAll:()=>[first,last]};const cleanup=manageDrawerFocus(panel,doc,trigger,()=>{closed=true;});assert.equal(focused,first);last.focus();let prevented=false;key({key:'Tab',shiftKey:false,preventDefault(){prevented=true;}});assert.equal(focused,first);assert(prevented);key({key:'Tab',shiftKey:true,preventDefault(){}});assert.equal(focused,last);key({key:'Escape',preventDefault(){}});assert(closed);cleanup();assert.equal(focused,'trigger');assert.equal(key,null);});
